const box = [
    "Trong truyện Cô bé quàng khăn đỏ, bà tiên xuất hiện khi nào?",
    "Xe nào không bao giờ giảm đi?",
    "Môn thể thao nào mà người ta chỉ đi bộ, ít khi chạy trên cỏ?",
    "Bonsai có nghĩa là gì?",
    "Con gì biết đi nhưng người ta vẫn nói nó không biết đi? (đố chữ)",
    "Khu vực Đông Nam Á gồm có bao nhiêu nước",
    "Rượu vang được lên men từ loại quả nào là chủ yếu?",
    "Con gì ăn lửa với than?",
    "Cây gì không có lá?",
    "Trong phim “Aladin và cây đèn thần”, thần đèn mặc áo màu gì?",
    "Nữ rapper Việt nào từng được tổng thống Obama yêu cầu đọc rap?",
    "Trong lúc Suboi đọc rap, tổng thống Obama đã làm gì?",    
    "Độc gì càng trúng càng thích?",
    "Loại quả nào ôm nỗi buồn 1 mình?",
    "Trong truyện Nàng tiên cá, khi có được đôi chân và được gặp lại hoàng tử, nàng tiên cá đã hát bài gì cho hoàng tử nghe?",
    "Tỉnh nào nước ta có tên nghe nửa ruộng nửa rừng (đố chữ)",
    "Loại bánh gì không ăn được? (đố chữ)",
    "Tác giả của Bình ngô đại cáo là ai?",
    "Loài động vật có vú lớn nhất hiện nay là con gì?",
    "Nỗi sợ lớn nhất của mèo máy Doremon là gì?",
    "Sa mạc nào có diện tích lớn nhất Thế Giới?",
    "So với Trái Đất, Mặt trăng lớn hơn hay nhỏ hơn?",
    "Ăn gì không no nhưng ai cũng thích?",
    "Cân nào bay được? (đố chữ)",
    "Dê sống ở núi gọi là sơn dương, vậy dê sống ở vùng biển gọi là gì? (đố chữ)?",
    "Dê nào mà các học trò không bao giờ thích? (đố chữ)",
    "Quan âm Thị Kính là vở diễn nổi tiếng của loại hình nghệ thuật nào?",
    "Từ nào trong tiếng Việt có 12 chữ Y? (đố chữ)",
    "Chổi nào biết bay?",
    "Hoa gì luôn ở phía sau?",
    "Hệ thống giao thông nước ta gồm bao nhiêu loại đường?",
    "Con gì không mắt, không tai, có đầu có cuối ai ai cũng nhờ?",
    "Xe gì ba bánh, chở hàng chở khách, bác tài phải đạp?",
    "“Một mẹ thường có sáu con, yêu thương mẹ sẻ nước non vơi đầy”. Đố là cái gì",
    "“Nắng mưa dầu tôi đâu bỏ bạn. Tắt lửa tối đèn sao bạn bỏ tôi”. Là cái gì?",
    "Thương yêu cần hành động, vậy thương gì cần nói nhiều? (Đố chữ)",
    "Trong MV bài hát “Thương em là điều anh không thể ngờ” Noo Phước Thịnh ăn gì?",
    "Cái gì cầm càng nhiều càng dễ mất? (Đố chữ)",
    "Kênh gì tàu thuyền không qua được?",
    "Kênh gì không có nước mà không phải kênh truyền hình?",
    "Cá gì biết làm toán (đố chữ)?",
    "Tảo gì bị cấm? (Đố chữ)",
    "Hồ nào biết hát biết ca?",
    "Bây giờ anh hơn em 5 tuổi. Vậy sau bao nhiêu năm nữa tuổi anh bằng tuổi em?",
    "Trong các họ Việt Nam, họ nào chiếm tỉ lệ nhiều nhất?",
    "Ở Châu Phi, chim cánh cụt sống ở nước nào?",
    "Đỏ hoe là tính từ mô tả cái gì?",
    "Đầu nào không có tóc mà không phải đầu trọc? ",
    "Khi nào thêm vào thì nhẹ, bớt đi thì nặng?",
    "Cua đá, cua đinh và cáy. Con nào không thuộc bộ cua?",
    "Cánh gì mà chẳng biết bay, chim hay sà xuống nơi đây kiếm mồi?",
    "Theo quan niệm y học, tại sao lại chọn ngón áp út để đeo nhẫn?",
    "Trong bài hát “đi cấy”, tác giả viết ăn cơm bằng gì?",
    "Cũng trong bài hát này,có bao nhiêu cô gái?",
    "Cái gì luôn đi đến mà không bao giờ đến nơi?",
    "Vuông vuông cửa đóng hai đầu, một trăm thằng chết lần hồi chui ra, thằng nào không mũ thì tha, thằng nào có mũ đem ra đốt đầu.",
    "Con đường nào mềm mại nhất thế giới? (Đố chữ)",
    "Con đường tơ lụa xưa từng đi ngang qua tỉnh nào ở Việt Nam?",
    "Con vật nào xuất hiện nhiều nhất trên con đường tơ lụa xưa?",
    "Quả bóng bowling có bao nhiêu lỗ tròn trên bề mặt?",
    "Loài chim nào không bao giờ bay, không bao giờ đi?",
    "Đường thốt nốt là đặc sản của tỉnh nào?",
    "“Hoàng tử mưa” là biệt danh của ca sĩ nào?",
    "“Công chúa bong bóng” là biệt danh của ai?",
    "“Thân hình đã chết từ lâu, mà hai con mắt, bộ râu vẫn còn” là cái gì?",
    "Tướng nào mà không cần ăn uống mà vẫn đánh trận được?",
    "Thành đi ra đường mặc áo màu xanh lá tại sao không ai tới gần? (Đố chữ).",
    "Cầu vồng có mấy màu? - Đáp án: Rất nhiều màu.",
    "Làm thế nào để nhìn thấu bên trong một con người?",
    "Cái gì của con chim mà lại có trên cơ thể con người?",
    "Tên đại dương tiếp giáp với phần đất liền của nước ta?",
    "Dãy núi nào là sự phân chia khí hậu giữa hai miền Bắc và Nam?",
    "“Lan lên lầu lấy lược Lan lấy lộn lưỡi lam Lan lên lầu lấy lại”.",
    "Hoa gì không phải hôm nay. (Chơi chữ)?",
    "Gọi là tên nhưng không bắn bằng cung là gì?",
    "Lão hạc trong tác phẩm “Lão hạc” tự tử bằng cách nào?",
    "Con công bị chết thì gọi là gì. (Đố chữ)?",
    "Quả gì không ai muốn ăn? ",
    "Công nào không có lông. (Đố chữ)?",
    "Công nào không biết múa mà lại biết đá bóng?",
    "Quả gì thêm huyền thì ngọt, thêm sắc thì chua.",
    "Con gì đầu chuột, đuôi heo?",
    "Vòng xoay chợ Bến Thành ở thành phố Hồ Chí Minh còn có tên gọi khác là gì?",
    "Vòng xoay bến Bạch Đằng ở thành phố Hồ Chí Minh còn có tên gọi khác là gì?",
    "Năm 2016, tổng thống Obama đã thưởng thức đặc sản gì ở Hà Nội?",
    "Nước nào nóng nhất?",
    "Sân bay nào không ở trên mặt đất?",
    "Ở đâu ngựa có thể qua sông, voi thì không?",
]



export default box